/**
 * 
 */
package com.ibsplc.itin.service;

import java.util.List;

import com.ibsplc.itin.vo.ApproverVO;
import com.ibsplc.itin.vo.BusinessOpportunityVO;
import com.ibsplc.itin.vo.EmployeeVO;
import com.ibsplc.itin.vo.MasterInfo;
import com.ibsplc.itin.vo.RequestVO;

/**
 * @author A-4211
 * 
 */

public interface ITinTravelServices {

	// Request initiator
	/**
	 * return all requests generated by the user
	 */
	// @param UserID specifies the id of the initiator
	public List<RequestVO> getTravelRequests(String userID, int start, int size);
	
	public List<RequestVO> getDTA(String dtaCode);

	public RequestVO updateRequest(RequestVO requestVO);

	public RequestVO createRequest(RequestVO requestVO);

	public MasterInfo getMasterInformation(String tokenDate);

	// Request Approver
	/**
	 * return all request generated by request-initiator
	 */

	// @param userID specifies the id of the approver
	public List<RequestVO> getApprovals(String userID, int start, int size);

	// @param userID specifies the id of the approver
	public boolean approve(ApproverVO approve);

	// return set of BO Projects
	public List<BusinessOpportunityVO> getBOProject(String costCenter, String userId);

	
	public EmployeeVO isValidUser(String userID);
	
	public boolean isValidToken();
	
	
	

}
